services:
    bitbag.payu.form.type.gateway_configuration:
        class: BitBag\PayUPlugin\Form\Type\PayUGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: payu, label: bitbag.payum_gateway_factory.payu }
            - { name: form.type }

    bitbag.payu.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [BitBag\PayUPlugin\PayUGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: payu }
