services:
    bitbag.payu_plugin.form.type.gateway_configuration:
        class: BitBag\PayUPlugin\Form\Type\PayUGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: payu, label: bitbag.payu_plugin.gateway_label }
            - { name: form.type }

    bitbag.payu_plugin.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [BitBag\PayUPlugin\PayUGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: payu }

    bitbag.payu_plugin.bridge.open_payu:
        class: BitBag\PayUPlugin\Bridge\OpenPayUBridge

    bitbag.payu_plugin.payu_action:
        class: BitBag\PayUPlugin\Action\PayUAction
        arguments: ['@bitbag.payu_plugin.bridge.open_payu', '@payum']
        tags:
            - { name: payum.action, factory: payu, alias: payum.action.set_payu }