services:
    bitbag.payu.form.type.gateway_configuration:
        class: BitBag\PayUPlugin\Form\Type\PayUGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: payu, label: bitbag.payu_plugin.gateway_label }
            - { name: form.type }

    bitbag.payu.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [BitBag\PayUPlugin\PayUGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: payu }

    bitbag.payu.open_payu_wrapper:
        class: BitBag\PayUPlugin\OpenPayUWrapper

    bitbag.payu.payu_action:
        class: BitBag\PayUPlugin\Action\PayUAction
        arguments: ['@bitbag.payu.open_payu_wrapper', '@payum']
        tags:
            - { name: payum.action, factory: payu, alias: payum.action.set_payu }